EStore/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static
from django.conf import settings

# API
from rest_framework import routers
from store.views import ProductViewSet
router = routers.DefaultRouter()
router.register(r'product', ProductViewSet)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls')),
    path('', include('customer.urls')),
    path('', include('cart.urls')),
    path('', include('admin_estore.urls')),
    path('', include('dashboard.urls')),
    path('', include('store_report.urls')),
    path('', include('analysis.urls')),
    path('api/', include(router.urls)),
    path('api-auth/', include('rest_framework.urls')),
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) 
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from cart.views import *


app_name = 'cart'
urlpatterns = [
    path('cart/', cart_detail, name='cart_detail'),
    path('buy-now/<int:product_id>/', buy_now, name='buy_now'),
    path('remove-cart/<int:product_id>/', remove_cart, name='remove_cart'),
    path('checkout/', checkout, name='checkout'),
]

customer/urls.py
from django.urls import path
from customer.views import *


app_name = 'customer'
urlpatterns = [
    path('login/', customer_login, name='customer_login'),
    
    path('logout/', customer_logout, name='customer_logout'),
    path('my-account/', my_account, name='my_account'),
]

store/urls.py
from django.urls import path
from store.views import *


app_name = 'store'
urlpatterns = [
    path('', index, name='index'),
    path('subcategory/<int:pk>/', subcategory, name='subcategory'),
    path('product/<int:pk>/', product_detail, name='product_detail'),
    path('contact/', contact, name='contact'),
    path('search/', search_products, name='search'),
    path('products-service/', products_service, name='products_service')
]

cart/models.py
from django.db import models
from customer.models import Customer
from store.models import Product


# Create your models here.
class Order(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    total = models.DecimalField(max_digits=10, decimal_places=2)
    status = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return f'Order {self.id}'


class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='items', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, related_name='order_items', on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return str(self.id)

store/forms.py
from django import forms
from store.models import Contact


class FormContact(forms.ModelForm):
    name = forms.CharField(max_length=300, widget=forms.TextInput(attrs={
        'class': 'form-control fh5co_contact_text_box',
        'placeholder': 'Enter Your Name',
    }))
    email = forms.EmailField(widget=forms.TextInput(attrs={
        'class': 'form-control fh5co_contact_text_box',
        'placeholder': 'Email',
    }))
    phone_number = forms.CharField(max_length=400, widget=forms.TextInput(attrs={
        'class': 'form-control fh5co_contact_text_box',
        'placeholder': 'Phone',
    }))
    subject = forms.CharField(max_length=400, widget=forms.TextInput(attrs={
        'class': 'form-control fh5co_contact_text_box',
        'placeholder': 'Subject',
    }))
    message = forms.CharField(widget=forms.Textarea(attrs={
        'class': 'form-control fh5co_contacts_message',
        'placeholder': 'Message',
    }))

    class Meta:
        model = Contact
        fields = '__all__'
        # fields = ('name', 'email', 'subject', 'message')

cart/views.py
from itertools import product
from django.shortcuts import render, redirect, get_object_or_404
from cart.cart import Cart
from store.models import Product
from cart.models import Order, OrderItem
from customer.models import Customer
from django.views.decorators.http import require_POST


# Create your views here.
def cart_detail(request):
    cart = Cart(request)

    # Mã giảm giá (coupon)
    list_ma_giam_gia = [
        {
            'TTTH': 0.8,
        },
        {
            'LNTRI': 0.9,
        },
    ]

    ma_giam_gia = ''
    giam_gia = 1
    if request.POST.get('btnMaGiamGia'):
        ma_giam_gia = request.POST.get('ma_giam_gia')  # TTTH
        for dict_ma_giam_gia in list_ma_giam_gia:
            if ma_giam_gia in dict_ma_giam_gia:
                cart_new = {}
                giam_gia = dict_ma_giam_gia[ma_giam_gia]
                for c in cart:
                    product_cart = {
                        str(c['product'].pk): {
                            'quantity': c['quantity'], 
                            'price': str(c['product'].price), 
                            'coupon': str(giam_gia)
                        }
                    }
                    cart_new.update(product_cart)

                    # Giữ lại số lượng mới trên ô tại thời điểm click nút
                    c['coupon'] = giam_gia
                else:
                    # Cập nhật session giỏ hàng (cart)
                    request.session['cart'] = cart_new
                break
        else:
            cart_new = {}
            for c in cart:
                product_cart = {
                    str(c['product'].pk): {
                        'quantity': c['quantity'], 
                        'price': str(c['product'].price), 
                        'coupon': str(giam_gia)
                    }
                }
                cart_new.update(product_cart)

                # Giữ lại số lượng mới trên ô tại thời điểm click nút
                c['coupon'] = giam_gia
            else:
                # Cập nhật session giỏ hàng (cart)
                request.session['cart'] = cart_new

    # Cập nhật giỏ hàng
    if request.POST.get('btnCapNhat'):
        cart_new = {}
        for c in cart:
            quantity_new = int(request.POST.get('quantity2' + str(c['product'].pk)))
            if quantity_new != 0:
                product_cart = {
                    str(c['product'].pk): {
                        'quantity': quantity_new, 
                        'price': str(c['product'].price), 
                        'coupon': str(c['coupon'])
                    }
                }
                cart_new.update(product_cart)
            else:
                # Xóa sản phẩm ra khỏi giỏ hàng khi số lượng mới = 0
                cart.remove(c['product'])

            # Giữ lại số lượng mới trên ô tại thời điểm click nút
            c['quantity'] = quantity_new
        else:
            # Cập nhật session giỏ hàng (cart)
            request.session['cart'] = cart_new

    return render(request, 'store/cart.html', {
        'cart': cart,
        'ma_giam_gia': ma_giam_gia,
    })


def checkout(request):
    # Kiểm tra trạng thái đăng nhập của khách hàng
    if 'session_KhachHang' not in request.session:
        return redirect('cart:cart_detail')

    # Đọc thông tin giỏ hàng từ session cart
    cart = Cart(request)

    # Thực hiện đặt hàng
    if request.POST.get('btnDatHang'):
        # Lấy thông tin khách hàng (người đặt hàng)
        customer = Customer.objects.get(pk=request.session.get('session_KhachHang')['id'])

        # Order
        order = Order()
        order.total = cart.get_final_total_price()
        order.customer = customer
        order.save()

        # OrderItem
        for c in cart:
            OrderItem.objects.create(order=order,
                                     product=c['product'],
                                     price=c['price'],
                                     quantity=c['quantity'])

        # Gửi mail

        # Xóa session cart khi đặt hàng thành công
        cart.clear()

        return render(request, 'cart/result.html', {
            'cart': cart,
        })

    return render(request, 'store/checkout.html', {
        'cart': cart,
    })


@require_POST
def buy_now(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    if request.POST.get('quantity'):
        cart.add(product, int(request.POST.get('quantity')))
    return redirect('cart:cart_detail')


@require_POST
def remove_cart(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')

store/views.py
from django.shortcuts import render, reverse, redirect
from store.models import *
from django.core.paginator import Paginator
from django.http import JsonResponse
from rest_framework import viewsets, permissions
from store.serializers import ProductSerializer
from urllib.parse import urlencode
from EStore.settings import MEDIA_ROOT
import pandas as pd
import re
import os
from store.forms import FormContact
# Create your views here.
def index(request):
    # Laptop
    subcategory_id_laptop = SubCategory.objects.filter(category_id=1).values_list('id')
    list_subcategory_id_laptop = []
    for subcategory_id in subcategory_id_laptop:
        list_subcategory_id_laptop.append(subcategory_id[0])
    # Lấy danh sách sản phẩm
    products_laptop = Product.objects.filter(subcategory__in=list_subcategory_id_laptop).order_by('-public_day')

     # CPU
    subcategory_id_cpu = SubCategory.objects.filter(category_id=2).values_list('id')
    print(subcategory_id_cpu)
    list_subcategory_id_cpu = []
    for subcategory_id in subcategory_id_cpu:
        list_subcategory_id_cpu.append(subcategory_id[0])
    # Lấy danh sách sản phẩm
    products_cpu = Product.objects.filter(subcategory__in=list_subcategory_id_cpu).order_by('-public_day')


    # top selling laptop
    subcategory_id_selling_latop = SubCategory.objects.filter(category_id=1).values_list('id')
    list_subcategory_id_selling_latop = []
    for subcategory_id in subcategory_id_selling_latop:
        list_subcategory_id_selling_latop.append(subcategory_id[0])
    # Lấy danh sách sản phẩm
    products_selling_latop = Product.objects.filter(subcategory__in=list_subcategory_id_selling_latop).order_by('-viewed')

     # top selling linkkien
    subcategory_id_selling_linh_kien = SubCategory.objects.filter(category_id=2).values_list('id')
    list_subcategory_id_selling_linh_kien = []
    for subcategory_id in subcategory_id_selling_linh_kien:
        list_subcategory_id_selling_linh_kien.append(subcategory_id[0])
    # Lấy danh sách sản phẩm
    products_selling_linh_kien = Product.objects.filter(subcategory__in=list_subcategory_id_selling_linh_kien).order_by('-viewed')

     # top selling gameinggear
    subcategory_id_selling_gear = SubCategory.objects.filter(category_id=3).values_list('id')
    list_subcategory_id_selling_gear = []
    for subcategory_id in subcategory_id_selling_gear:
        list_subcategory_id_selling_gear.append(subcategory_id[0])
    # Lấy danh sách sản phẩm
    products_selling_gear = Product.objects.filter(subcategory__in=list_subcategory_id_selling_gear).order_by('-viewed')
    
    return render(request, 'store/index.html', {
    'products_laptop':products_laptop,
    'products_cpu':products_cpu,
    'products_selling_latop':products_selling_latop,
    'products_selling_linh_kien':products_selling_linh_kien,
    'products_selling_gear':products_selling_gear,
    })
def subcategory(request, pk):
     # Danh sách subcategory
    subcategories = SubCategory.objects.order_by('name')

    if pk == 0:
        # Đọc tất cả sp
        products = Product.objects.order_by('-public_day')
        title_subcategory = 'Tất cả sản phẩm (' + str(products.count()) + ')'
    else:
        # Đọc sản phẩm theo subcategory_id
        products = Product.objects.filter(subcategory=pk).order_by('-public_day')
        name_subcategory = SubCategory.objects.get(pk=pk)
        title_subcategory = str(name_subcategory) + ' (' + str(products.count()) + ')'

    # Lọc theo range giá
    tu_gia = ''
    den_gia = ''
    tu_khoa = ''
    if request.GET.get('from_price'):
        tu_gia = float(request.GET.get('from_price'))
        den_gia = float(request.GET.get('to_price'))
        tu_khoa = request.GET.get('product_name')

        # Nếu có chứa từ khóa tìm kiếm (product_name) 
        if tu_khoa != '':
            products = Product.objects.filter(name__contains=tu_khoa).order_by('-public_day')

        products = [product for product in products if tu_gia <= product.price <= den_gia]  # list comprehension
        title_subcategory = 'Tìm thấy {} sản phẩm trong khoảng giá {} - {}'.format(len(products), '{:,}'.format(int(tu_gia)), '{:,}'.format(int(den_gia)))

    # Phân trang
    page = request.GET.get('page', 1)
    paginator = Paginator(products, 15)
    products_pager = paginator.page(page)
    return render(request,'store/product-list.html',{
        'subcategories': subcategories,
        'products': products_pager,
        'title_subcategory': title_subcategory,
        'tu_gia': tu_gia,
        'den_gia': den_gia,
    })

def search_products(request):
    tu_khoa = ''
    if request.GET.get('product_name'):
        tu_khoa = request.GET.get('product_name').strip()

        products = Product.objects.filter(name__contains=tu_khoa).order_by('-public_day')
        title_subcategory = 'Tìm thấy {} sản phẩm với từ khóa "{}"'.format(products.count(), tu_khoa)

    # Phân trang
    page = request.GET.get('page', 1)
    paginator = Paginator(products, 15)
    products_pager = paginator.page(page)

    tu_gia = ''
    den_gia = ''
    if request.GET.get('from_price'):
        tu_gia = float(request.GET.get('from_price'))
        den_gia = float(request.GET.get('to_price'))
        tu_khoa = request.GET.get('product_name')

        base_url = reverse('store:subcategory', kwargs={'pk': 0})
        query_string = urlencode({
            'from_price': round(tu_gia),
            'to_price': round(den_gia),
            'product_name': tu_khoa
        })
        url = '{}?{}'.format(base_url, query_string)
        return redirect(url)


    return render(request, 'store/product-list.html', {
        'tu_khoa': tu_khoa,
        'title_subcategory': title_subcategory,
        'products': products_pager,
    })
#Web Service 
def products_service(request):
    products = Product.objects.all()
    result_list = list(products.values('name', 'price', 'public_day'))
    return JsonResponse(result_list, safe=False)


# Django Rest Framework
class ProductViewSet(viewsets.ModelViewSet):
    queryset = Product.objects.all()
    serializer_class = ProductSerializer
    permission_classes = [permissions.IsAuthenticatedOrReadOnly]


def product_detail(request, pk):
    # Danh sách subcategory
    subcategories = SubCategory.objects.order_by('name')

    # Lấy sản phẩm
    product = Product.objects.get(pk=pk)

    # Sản phẩm liên quan
    id_subcategory = product.subcategory.pk
    products_related = Product.objects.filter(subcategory=id_subcategory).exclude(pk=pk).order_by('-public_day')[:20]

    # Tên danh mục
    subcategory_name = product.subcategory

    #sản phẩm nhiều lượt xem
    view_product=Product.objects.order_by('-viewed')[:20]
    # Hiển thị sản phẩm thường được mua kèm
    rules = pd.read_csv(os.path.join(MEDIA_ROOT, 'rules.csv'), squeeze=True, index_col=0)
    lst = rules.values.tolist()
    list_rules = []
    for item in lst:
        if str(pk) in re.findall('\d+[, \d+]*', item[0])[0].split(','):
            list_rules = re.findall('\d+[, \d+]*', item[1])[0].split(',')
    list_asc_products = []
    for i in list_rules:
        list_asc_products.append(Product.objects.get(pk=int(i)))

    return render(request, 'store/product-detail.html', {
        'subcategories': subcategories,
        'product': product,
        'products_related': products_related,
        'subcategory_name': subcategory_name,
        'id_subcategory': id_subcategory,
        'list_asc_products': list_asc_products,
        'view_product':view_product,
    })

def contact(request):
    form = FormContact()
    result = ''
    if request.POST.get('btnSend'):  # sự kiện click nút
        form = FormContact(request.POST, Contact)
        if form.is_valid():
            request.POST._mutable = True
            post = form.save(commit=False)
            post.name = form.cleaned_data['name']
            post.email = form.cleaned_data['email']
            post.subject = form.cleaned_data['subject']
            post.message = form.cleaned_data['message']
            post.save()

            result = '''
            <div class="alert alert-success" role="alert">
                Gửi thông tin thành công.
            </div>
            '''
            
    return render(request, 'store/contact.html', {
        'form': form,
        'result': result,
    })

store/templates/store/_Master.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		 <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
		 <title>{% block title_tab %}{% endblock %}</title>

		<!-- Google font -->
		<link href="https://fonts.googleapis.com/css?family=Montserrat:400,500,700" rel="stylesheet">

		<!-- Bootstrap -->
		<link type="text/css" rel="stylesheet" href="{% static 'store/css/bootstrap.min.css' %}"/>

		<!-- Slick -->
		<link type="text/css" rel="stylesheet" href="{% static 'store/css/slick.css' %}"/>
		<link type="text/css" rel="stylesheet" href="{% static 'store/css/slick-theme.css'%}"/>

		<!-- nouislider -->
		<link type="text/css" rel="stylesheet" href="{% static 'store/css/nouislider.min.css'%}"/>

		<!-- Font Awesome Icon -->
		<link rel="stylesheet" href="{% static 'store/css/font-awesome.min.css'%}">

		<!-- Custom stlylesheet -->
		<link type="text/css" rel="stylesheet" href="{% static 'store/css/style.css'%}"/>

		<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
		<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
		<!--[if lt IE 9]>
		  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
		  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
		<![endif]-->
		<style>
			.dropbtn {
			  background-color: #ffffff;
			  color: rgb(0, 0, 0);
			  padding: 16px;
			  font-size: 16px;
			  border: none;
			}
			
			.dropdown {
			  position: relative;
			  display: inline-block;
			}
			
			.dropdown-content {
			  display: none;
			  position: absolute;
			  background-color: #f1f1f1;
			  min-width: 160px;
			  box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
			  z-index: 1;
			}
			
			.dropdown-content a {
			  color: black;
			  padding: 12px 16px;
			  text-decoration: none;
			  display: block;
			}
			
			.dropdown-content a:hover {background-color: #ddd;}
			
			.dropdown:hover .dropdown-content {display: block;}
			
			.dropdown:hover .dropbtn {background-color: #e7e7e7;}





			.dropbtn-gg {
				background-color: #1E1F29;
			  color: rgb(0, 0, 0);
			  padding: 12px;
			  font-size: 16px;
			  border: none;
			}
			
			.dropdown-gg {
			  position: relative;
			  display: inline-block;
			}
			
			.dropdown-content-gg {
			  display: none;
			  position: absolute;
			  background-color: #1E1F29;
			  min-width: 160px;
			  box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
			  z-index: 1;
			}
			
			.dropdown-content-gg a {
			  color: black;
			  padding: 12px 16px;
			  text-decoration: none;
			  display: block;
			}
			
			.dropdown-content-gg a:hover {background-color: #1E1F29;}
			
			.dropdown-gg:hover .dropdown-content-gg {display: block;}
			
			.dropdown-gg:hover .dropbtn-gg {background-color: #1E1F29;}
			</style>
    </head>
	<body>
		<!-- HEADER -->
		<header>
			<!-- TOP HEADER -->
			<div id="top-header">
				<div class="container">
					<ul class="header-links pull-left">
						<li><a href="#"><i class="fa fa-phone"></i> +(84)917074775</a></li>
						<li><a href="#"><i class="fa fa-envelope-o"></i> chaugiahuy0210@gmail.com</a></li>
						
					</ul>
					<ul class="header-links pull-right">
						
						<li class="dropdown-gg" >
							{% if request.session.session_KhachHang %}
							<a class="dropbtn-gg" href="#">
							<i class="fa fa-user-o"></i> {{ request.session.session_KhachHang.first_name }} {{ request.session.session_KhachHang.last_name }}</a>
							<div class="dropdown-content-gg">
								<a href="{% url 'customer:my_account' %}" class="dropdown-item">Thông tin của tôi</a>
								<a href="{% url 'customer:customer_logout' %}" class="dropdown-item">Đăng xuất</a>
							</div>
						{% else %}
							<a href="{% url 'customer:customer_login' %}" class="nav-item nav-link active">Đăng nhập</a>
						{% endif %}
						</li>
					</ul>
				</div>
			</div>
			<!-- /TOP HEADER -->

			<!-- MAIN HEADER -->
			<div id="header">
				<!-- container -->
				<div class="container">
					<!-- row -->
					<div class="row">
						<!-- LOGO -->
						<div class="col-md-3">
							<div class="header-logo">
								<a href="{% url 'store:index' %}" class="logo">
									
									<img src="{% static 'store/img/logo.png' %}" alt="">
								</a>
							</div>
						</div>
						<!-- /LOGO -->

						<!-- SEARCH BAR -->
						<div class="col-md-6">
							<div class="header-search">
								<form method="get" action="{% url 'store:search' %}">
									<div class="search">
									<!-- <select class="input-select">
										<option value="0">All Categories</option>
										<option value="1">Category 01</option>
										<option value="1">Category 02</option>
									</select> -->
									<input type="text" placeholder="Nhập từ khóa tìm kiếm" name="product_name" value="{{ tu_khoa }}">
									<button>Search</button>
								</div>
								</form>
							</div>
						</div>
						<!-- /SEARCH BAR -->

						<!-- ACCOUNT -->
						<div class="col-md-3 clearfix">
							<div class="header-ctn">
						

								<!-- Cart -->
								<div class="dropdown">
									<a href="{% url 'cart:cart_detail' %}" class="btn cart" data-toggle="dropdown" aria-expanded="true">
										<i class="fa fa-shopping-cart"></i>
										
										<div class="qty">{{ cart|length }}</div>
									</a>

								</div>
								<!-- /Cart -->

								<!-- Menu Toogle -->
								<div class="menu-toggle">
									<a href="#">
										<i class="fa fa-bars"></i>
										<span>Menu</span>
									</a>
								</div>
								<!-- /Menu Toogle -->
							</div>
						</div>
						<!-- /ACCOUNT -->
					</div>
					<!-- row -->
				</div>
				<!-- container -->
			</div>
			<!-- /MAIN HEADER -->
		</header>
		<!-- /HEADER -->

		<!-- NAVIGATION -->
		<nav id="navigation">
			<!-- container -->
			<div class="container">
				<!-- responsive-nav -->
				<div id="responsive-nav">
					<!-- NAV -->
					<ul class="main-nav nav navbar-nav">
						<li class="dropdown" ><a class="dropbtn" href="{% url 'store:index' %}">Trang chủ</a></li>
						<li class="dropdown">
							<a class="dropbtn" href="{% url 'store:subcategory' 1 %}">Laptop</a>
							<div class="dropdown-content">
							  <a href="{% url 'store:subcategory' 1 %}">Laptop Acer</a>
							  <a href="{% url 'store:subcategory' 2 %}">Laptop Asus</a>
							  <a href="{% url 'store:subcategory' 3 %}">Laptop MSI</a>
							  <a href="{% url 'store:subcategory' 4 %}">Laptop Lenovo</a>
							</div>
						</li>
						<li class="dropdown">
							<a class="dropbtn" href="{% url 'store:subcategory' 5 %}">Link kiện</a>
							<div class="dropdown-content">
							  <a href="{% url 'store:subcategory' 5 %}">CPU</a>
							  <a href="{% url 'store:subcategory' 6 %}">RAM</a>
							  <a href="{% url 'store:subcategory' 7 %}">HDD</a>
							  <a href="{% url 'store:subcategory' 8 %}">Nguồn máy tính</a>
							</div>
						</li>
						<li class="dropdown">
							<a class="dropbtn" href="{% url 'store:subcategory' 9 %}">Gaming gear</a>
							<div class="dropdown-content">
							  <a href="{% url 'store:subcategory' 9 %}">Bàn phím</a>
							  <a href="{% url 'store:subcategory' 10 %}">Chuột</a>
							  <a href="{% url 'store:subcategory' 11 %}">Tai nghe</a>
				
							</div>
						</li>
						<li class="dropdown"><a class="dropbtn" href="{% url 'store:contact' %}">Contact</a></li>
						
					</ul>
					<!-- /NAV -->
				</div>
				<!-- /responsive-nav -->
			</div>
			<!-- /container -->
		</nav>
		<!-- /NAVIGATION -->

		{% block main_content %}{% endblock %}   

        
		<!-- FOOTER -->
		<footer id="footer">
			<!-- top footer -->
			<div class="section">
				<!-- container -->
				<div class="container">
					<!-- row -->
					<div class="row">
						<div class="col-md-3 col-xs-6">
							<div class="footer">
								<h3 class="footer-title">About Us</h3>
								<p>Chuyên bán bán link kiện, laptop, và phụ kiện chơi game</p>
								<ul class="footer-links">
									<li><a href="#"><i class="fa fa-map-marker"></i>1734 Stonecoal Road</a></li>
									<li><a href="#"><i class="fa fa-phone"></i>+021-95-51-84</a></li>
									<li><a href="#"><i class="fa fa-envelope-o"></i>email@email.com</a></li>
								</ul>
							</div>
						</div>

						<div class="col-md-3 col-xs-6">
							<div class="footer">
								<h3 class="footer-title">Categories</h3>
								<ul class="footer-links">
									<li><a href="{% url 'store:subcategory' 1 %}">Latop</a></li>
									<li><a href="{% url 'store:subcategory' 5 %}">Linkien</a></li>
									<li><a href="{% url 'store:subcategory' 9 %}">Gaming gear </a></li>

								</ul>
							</div>
						</div>

						<div class="clearfix visible-xs"></div>

					</div>
					<!-- /row -->
				</div>
				<!-- /container -->
			</div>
			<!-- /top footer -->

			<!-- bottom footer -->
			<div id="bottom-footer" class="section">
				<div class="container">
					<!-- row -->
					<div class="row">
						<div class="col-md-12 text-center">
							<ul class="footer-payments">
								<li><a href="#"><i class="fa fa-cc-visa"></i></a></li>
								<li><a href="#"><i class="fa fa-credit-card"></i></a></li>
								<li><a href="#"><i class="fa fa-cc-paypal"></i></a></li>
								<li><a href="#"><i class="fa fa-cc-mastercard"></i></a></li>
								<li><a href="#"><i class="fa fa-cc-discover"></i></a></li>
								<li><a href="#"><i class="fa fa-cc-amex"></i></a></li>
							</ul>
							<span style="   opacity: 0;" class="copyright">
								<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
								Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
							<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
							</span>
						</div>
					</div>
						<!-- /row -->
				</div>
				<!-- /container -->
			</div>
			<!-- /bottom footer -->
		</footer>
		<!-- /FOOTER -->

		<!-- jQuery Plugins -->
		<script src="{% static 'store/js/jquery.min.js'%}"></script>
		<script src="{% static 'store/js/bootstrap.min.js'%}"></script>
		<script src="{% static 'store/js/slick.min.js'%}"></script>
		<script src="{% static 'store/js/nouislider.min.js'%}"></script>
		<script src="{% static 'store/js/jquery.zoom.min.js'%}"></script>
		<script src="{% static 'store/js/main.js'%}"></script>

	</body>
</html>