EStore/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static
from django.conf import settings

# API
from rest_framework import routers
from store.views import ProductViewSet
router = routers.DefaultRouter()
router.register(r'product', ProductViewSet)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls')),
    path('', include('customer.urls')),
    path('', include('cart.urls')),
    path('', include('admin_estore.urls')),
    path('', include('dashboard.urls')),
    path('', include('store_report.urls')),
    path('', include('analysis.urls')),
    path('api/', include(router.urls)),
    path('api-auth/', include('rest_framework.urls')),
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) 
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin_estore/urls.py
from django.urls import path
from admin_estore.views import *


app_name = 'admin_estore'
urlpatterns = [
    path('user-auth/', user_auth, name='user_auth'),
    path('user-logout/', logout_user_auth, name='logout_user_auth'),
]

cart/urls.py
from django.urls import path
from cart.views import *


app_name = 'cart'
urlpatterns = [
    path('cart/', cart_detail, name='cart_detail'),
    path('buy-now/<int:product_id>/', buy_now, name='buy_now'),
    path('remove-cart/<int:product_id>/', remove_cart, name='remove_cart'),
    path('checkout/', checkout, name='checkout'),
]

admin_estore/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class UserProfileInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.PROTECT)
    portfolio = models.URLField(blank=True, null=True)
    image = models.ImageField(upload_to='users/', default='users/no_avatar.png')

    def __str__(self):
        return self.user.username

admin_estore/forms.py
from django import forms
from django.contrib.auth.models import User
from admin_estore.models import UserProfileInfo


class FormUser(forms.ModelForm):
    username = forms.CharField(label='Username', widget=forms.TextInput(attrs={
        'class': 'form-control',
    }))
    email = forms.EmailField(label='Email', widget=forms.EmailInput(attrs={
        'class': 'form-control',
    }))
    password = forms.CharField(label='Password', widget=forms.PasswordInput(attrs={
        'class': 'form-control',
    }))
    confirm_password = forms.CharField(label='Confirm Password', widget=forms.PasswordInput(attrs={
        'class': 'form-control',
    }))

    class Meta:
        model = User
        fields = ['username', 'email', 'password']


class FormUserProfileInfo(forms.ModelForm):
    portfolio = forms.URLField(label='Portfolio', widget=forms.TextInput(attrs={
        'class': 'form-control',
    }))
    image = forms.ImageField(label='Image', widget=forms.FileInput(attrs={
        'class': 'form-control-file',
    }))
    
    class Meta:
        model = UserProfileInfo
        exclude = ['user']

admin_estore/views.py
from django.shortcuts import render, redirect
from admin_estore.forms import FormUser, FormUserProfileInfo
from django.contrib.auth import authenticate, login, logout


# Create your views here.
def user_auth(request):
    # =========== SIGNUP
    frm_user = FormUser()
    frm_profile = FormUserProfileInfo()

    # Thực hiện lưu thông tin
    result_register = ''
    if request.POST.get('btnRegister'):
        frm_user = FormUser(request.POST)
        frm_profile = FormUserProfileInfo(request.POST, request.FILES)
        if frm_user.is_valid() and frm_profile.is_valid():
            if frm_user.cleaned_data['password'] == frm_user.cleaned_data['confirm_password']:
                # === GHI VÀO CDSL
                # 1. User
                user = frm_user.save()
                user.set_password(user.password)
                user.save()

                # 2. UserProfileInfo
                profile = frm_profile.save(commit=False)
                profile.user = user
                profile.save()

                result_register = '''
                <div class="alert alert-success" role="alert">
                    Đăng kí tài khoản admin thành công.
                </div>
                '''
            else:
                result_register = '''
                <div class="alert alert-danger" role="alert">
                    Mật khẩu và Xác nhận mật khẩu không khớp. Vui lòng kiểm tra lại.
                </div>
                '''
        else:
            result_register = '''
            <div class="alert alert-danger" role="alert">
                Dữ liệu nhập không hợp lệ. Vui lòng kiểm tra lại.
            </div>
            '''

    # ========== LOGIN
    result_login = ''
    if request.POST.get('btnLogin'):
        # Gán biến
        username = request.POST.get('username')
        password = request.POST.get('password')

        # Xác thực
        user = authenticate(request, username=username, password=password)

        # Xét điều kiện
        if user is not None:
            login(request, user)
            return redirect('admin_estore:user_auth')
        else:
            result_login = '''
            <div class="alert alert-danger" role="alert">
                Đăng nhập không thành công. Vui lòng kiểm tra lại thông tin nhập.
            </div>
            '''

    return render(request, 'admin_estore/user_auth.html', {
        'frm_user': frm_user,
        'frm_profile': frm_profile,
        'result_register': result_register,
        'result_login': result_login,
    })


def logout_user_auth(request):
    logout(request)
    return redirect('admin_estore:user_auth')

admin_estore/templates/admin_estore/user_auth.html
<!doctype html>
<html lang="en">


<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
       
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css"
        integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">


  <title>User auth</title>
</head>

<body>
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <br>
                <h2>SIGNUP</h2>
                <hr>
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ result_register|safe }}
                    <div class="form-group">
                        {{ frm_user.username.label }}
                        {{ frm_user.username }}
                    </div>
                    <div class="form-group">
                        {{ frm_user.email.label }}
                        {{ frm_user.email }}
                    </div>
                    <div class="form-group">
                        {{ frm_user.password.label }}
                        {{ frm_user.password }}
                    </div>
                    <div class="form-group">
                        {{ frm_user.confirm_password.label }}
                        {{ frm_user.confirm_password }}
                    </div>
                    <div class="form-group">
                        {{ frm_profile.portfolio.label }}
                        {{ frm_profile.portfolio }}
                    </div>
                    <div class="form-group">
                        {{ frm_profile.image.label }}
                        {{ frm_profile.image }}
                    </div>
                    <button type="submit" class="btn btn-primary" name="btnRegister" value="Register">Register</button>
                </form>
            </div>
            <div class="col-md-6">
                <br>
                <h2>LOGIN</h2>
                <hr>
                <form method="post">
                    {% csrf_token %}
                    {% if request.user.is_authenticated %}
                        <div><label>Xin chào, {{ request.user }}</label></div>
                        <a href="{% url 'admin_estore:logout_user_auth' %}" class="btn btn-primary">Logout</a>
                    {% else %}
                        <div class="form-group">
                            <label>Username</label>
                            <input type="text" class="form-control" name="username">
                        </div>
                        <div class="form-group">
                            <label>Password</label>
                            <input type="password" class="form-control" name="password">
                        </div>
                        <button type="submit" class="btn btn-primary" name="btnLogin" value="Login">Login</button>
                    {% endif %}
                </form>
            </div>
        </div>
        
    </div>
       
    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct"
        crossorigin="anonymous"></script>
</body>

</html>